#!/usr/bin/env bash

set -eux

DOTS_ROOT=$(git rev-parse --show-toplevel)

cd $DOTS_ROOT

# Set all directories (including subdirectories) to 755
find . -type d -exec chmod 755 {} \;

# Set all files under 'units' and 'lib' directories to 755
find ./units ./lib -type f -exec chmod 755 {} \;

# Set all other files to 644
find . -type f \( ! -path "./units/*" ! -path "./lib/*" \) -exec chmod 644 {} \;


