#!/usr/bin/env bash

# for each unit in the units directory, add an empty function "post_install_message" that echos an empty string if it doesn't exist
for unit in /home/kindrobot/Nextcloud/dots/units/*; do
    if [[ -f "$unit" ]]; then
        if ! grep -q "post_install_message" "$unit"; then
            echo -e "\npost_install_message() {\n  echo \"\"\n}" >> "$unit"
        fi
    fi
done