#!/usr/bin/env bash

description() {
    echo "Install apt CLI packages"
}

dependencies() {
    echo "apt-update"
}

main() {
    sudo apt install \
        curl \
        golang \
        fd-find \
        fish \
        git \
        golang \
        mosh \
        neovim \
        php \
        silversearcher-ag \
        trash-cli \
        tree \
        wget \
        libspa-0.2-bluetooth \
        wl-clipboard \
        -y
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
