#!/usr/bin/env bash

description() {
    echo "Install deb-bin package manager"
}

dependencies() {
    echo "apt-update"
}

main() {
    DOTS_ROOT=$(git rev-parse --show-toplevel)

    sudo apt install $DOTS_ROOT/assets/deb-get_0.4.3-1_all.deb

    sudo deb-get install \
      code \
      slack-desktop \
      vivaldi-stable
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
