#!/usr/bin/env bash

description() {
    echo "set up fdfind and alias it to fd"
}

dependencies() {
    echo "profile-home apt-update"
}

main() {
    set -eu

    sudo apt install fd-find -y

    DOTS_ROOT=$(git rev-parse --show-toplevel)
    ln -sf $DOTS_ROOT/configs/home-profile.d/fdfind $HOME/.profile.d/fdfind
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi