#!/usr/bin/env bash

description() {
    echo "Install fish shell"
}

dependencies() {
    echo "apt-update"
}

main() {
    sudo apt install fish -y
    chsh -s /usr/bin/fish

    fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
    fish -c 'fisher install jethrokuan/z'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi


