#!/usr/bin/env bash

description() {
    echo "Link git config"
}

dependencies() {
    echo ""
}

main() {
    set -eux

    DOTS_ROOT=$(git rev-parse --show-toplevel)

    ln -fs $DOTS_ROOT/configs/git_config $HOME/.gitconfig
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi