#!/usr/bin/env bash

description() {
    echo "Install kubectl, k9s, and helm"
}

dependencies() {
    echo "apt-update"
}

main() {
    sudo apt install -y kubernetes-client

    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    sudo apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt-get update
    sudo apt-get install helm -y

    cd $(mktemp -d)
    wget https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_linux_amd64.deb
    sudo apt install ./k9s_linux_amd64.deb -y
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi