#!/usr/bin/env bash

description() {
    echo "Set up user profile"
}

dependencies() {
    echo ""
}

main() {
    set -eu
    DOTS_ROOT=$(git rev-parse --show-toplevel)
    ln -sf $DOTS_ROOT/configs/profile $HOME/.profile
    mkdir -p $HOME/.profile.d
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi