#!/usr/bin/env bash

set -eux

sudo apt install libinput-tools

kwriteconfig5 --file $HOME/.config/kxkbrc --group Layout --key Options caps:swapescape

touchpad_input=$(sudo libinput list-devices | grep Touchpad | awk '{$1=""; print $0}' | sed 's/^ *//')
vendor_id=$(echo $touchpad_input | awk '{split($2, id, ":"); printf "%d\n", "0x" id[1]}')
product_id=$(echo $touchpad_input | awk '{split($2, id, ":"); printf "%d\n", "0x" id[2]}')

kwriteconfig5 --file $HOME/.config/kcminputrc --group Libinput --group $vendor_id --group $product_id --group "$touchpad_input" --key TapToClick --type bool true

echo "YOU WILL LIKELY NEED TO RESTART"
