#!/usr/bin/env bash

kwriteconfig5 --file $HOME/.config/kdedefaults/kdeglobals --group General --key ColorScheme "BreezeDark"
kwriteconfig5 --file $HOME/.config/kdedefaults/kdeglobals --group Icons --key Theme "breeze-dark"


kwriteconfig5 --file $HOME/.config/kactivitymanagerdrc --group activities --key 5e19ceef-21a0-42aa-9adc-29648f3405a7 Default
kwriteconfig5 --file $HOME/.config/kactivitymanagerdrc --group activities --key 32597efd-e279-4496-a2f1-be96882d06bf WMF

kwriteconfig5 --file $HOME/.config/kactivitymanagerdrc --group activities-icons --key 32597efd-e279-4496-a2f1-be96882d06bf globe

kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key Description "Application settings for org.keepassxc.KeePassXC"
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key activity "00000000-0000-0000-0000-000000000000"
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key activityrule "3"
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key wmclass "keepassxc org.keepassxc.KeePassXC"
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key wmclasscomplete --type bool true
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "8bb35848-a9dd-416e-931a-dd072e93ec95" --key wmclassmatch "1"

kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "General" --key count "1"
kwriteconfig5 --file $HOME/.config/kwinrulesrc --group "General" --key rules "8bb35848-a9dd-416e-931a-dd072e93ec95"

qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
var allActivities = activities();
var defaultActivity = "Default"; // The name of the default activity
var wmfActivity = "WMF"; // The name of the WMF activity

for (var i = 0; i < allActivities.length; i++) {
    var activityId = allActivities[i];
    var name = activityName(activityId);
    if (name === defaultActivity) {
        desktopsForActivity(activityId).forEach(function(desktop) {
            desktop.wallpaperPlugin = "org.kde.image";
            desktop.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"];
            desktop.writeConfig("Image", "file:///home/kindrobot/Nextcloud/dots/assets/lofi_fire_wallpaper.jpg");
        });
    } else if (name === wmfActivity) {
        desktopsForActivity(activityId).forEach(function(desktop) {
            desktop.wallpaperPlugin = "org.kde.image";
            desktop.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"];
            desktop.writeConfig("Image", "file:///home/kindrobot/Nextcloud/dots/assets/waporwada.webp");
        });
    }
}
'

qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
var panel = panels()[0]; // Access the main panel (adjust index if necessary)

// Add the Activity widget to the panel
var activityWidget = panel.addWidget("org.kde.plasma.activities");

// Move it to the far right
var widgets = panel.widgetIds;
activityWidget.currentConfigGroup = ["General"];
activityWidget.writeConfig("compactRepresentation", true); // Icon-only mode

// Move the widget to the far-right position
activityWidget.location = widgets.length - 1;
panel.reloadConfig();
'