#!/usr/bin/env bash

description() {
    echo "Install keepassxc"
}

dependencies() {
    echo "apt-update"
}

main() {
    sudo apt install wget -y
    temp_dir=$(mktemp -d)
    cd $temp_dir
    wget https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
    sudo install skaffold-linux-amd64 /usr/local/bin/skaffold
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi