#!/usr/bin/env bash

description() {
    echo "Link ssh config"
}

dependencies() {
    echo ""
}

main() {
    set -eux

    DOTS_ROOT=$(git rev-parse --show-toplevel)

    mkdir -p $HOME/.ssh
    ln -fs $DOTS_ROOT/configs/ssh_config $HOME/.ssh/config
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi