#!/usr/bin/env bash

description() {
    echo 'set up $SSH_AUTH_SOCK'
}

dependencies() {
    echo "profile-home"
}

main() {
    set -eu
    DOTS_ROOT=$(git rev-parse --show-toplevel)
    ln -sf $DOTS_ROOT/configs/home-profile.d/ssh-agent $HOME/.profile.d/ssh-agent
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi