name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p dist
          # Linux
          GOOS=linux GOARCH=amd64 go build -o dist/yadu-linux-amd64 cmd/yadu/main.go
          GOOS=linux GOARCH=arm64 go build -o dist/yadu-linux-arm64 cmd/yadu/main.go
          GOOS=linux GOARCH=arm go build -o dist/yadu-linux-arm cmd/yadu/main.go
          GOOS=linux GOARCH=riscv64 go build -o dist/yadu-linux-riscv64 cmd/yadu/main.go
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -o dist/yadu-darwin-amd64 cmd/yadu/main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/yadu-darwin-arm64 cmd/yadu/main.go
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -o dist/yadu-windows-amd64.exe cmd/yadu/main.go
          
          # Create checksums
          cd dist && sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/yadu-linux-amd64
            dist/yadu-linux-arm64
            dist/yadu-linux-arm
            dist/yadu-linux-riscv64
            dist/yadu-darwin-amd64
            dist/yadu-darwin-arm64
            dist/yadu-windows-amd64.exe
            dist/checksums.txt